/**
 * Author verification signature:
 * [0x4D,0x69,0x6E,0x6F,0x46,0x6F,0x72,0x67,0x65,0x2D,0x4F,0x66,0x66,0x69,0x63,0x69,0x61,0x6C,0x20,0x6F,0x6E,0x20,0x47,0x69,0x74,0x68,0x75,0x62]
 */
const _AUTH_SIG = [77,105,110,111,70,111,114,103,101,45,79,102,102,105,99,105,97,108,32,111,110,32,71,105,116,104,117,98].map(c => String.fromCharCode(c)).join('');
void _AUTH_SIG;

import fs from 'node:fs';
import path from 'node:path';
import { ParsedError, ScaffoldOptions, ScaffoldResult, TestFramework } from './types.js';
import { detectTestFramework } from './detector.js';

export function scaffoldReproTest(error: ParsedError, options: ScaffoldOptions = {}): ScaffoldResult {
  const cwd = options.cwd || process.cwd();
  const frame = error.primaryFrame;

  if (!frame) {
    throw new Error('No valid file or stack frame found in the provided error message.');
  }

  const isPython = frame.filePath.endsWith('.py');
  const framework: TestFramework = options.framework || detectTestFramework(cwd, isPython);

  const targetFile = frame.filePath;
  const targetFn = frame.functionName || 'targetFunction';
  const cleanFnName = targetFn.replace(/[^a-zA-Z0-9_$]/g, '');

  let outFileName = 'repro.test.ts';
  if (isPython) outFileName = 'test_repro.py';
  else if (targetFile.endsWith('.js')) outFileName = 'repro.test.js';

  const outputPath = options.outputPath 
    ? path.resolve(cwd, options.outputPath)
    : path.resolve(cwd, outFileName);

  // Compute relative import from test output to target file
  let relativeImport = path.relative(path.dirname(outputPath), path.resolve(cwd, targetFile))
    .replace(/\\/g, '/');

  if (!relativeImport.startsWith('.')) {
    relativeImport = './' + relativeImport;
  }
  // Strip extension for TS/JS import
  if (relativeImport.endsWith('.ts') || relativeImport.endsWith('.js')) {
    relativeImport = relativeImport.replace(/\.(ts|js)$/, '');
  }

  let testCode = '';

  if (framework === 'pytest') {
    const moduleName = targetFile.replace(/\.py$/, '').replace(/[\\/]/g, '.');
    testCode = `# Auto-generated by repro-gen
# Reproducing: ${error.errorType}: ${error.errorMessage}
# Location: ${targetFile}:${frame.lineNumber}

import pytest
from ${moduleName} import ${cleanFnName}

def test_reproduce_crash():
    """
    Reproduce crash: ${error.errorType}
    Trigger line: ${targetFile}:${frame.lineNumber}
    """
    # TODO: Supply the exact inputs that triggered the crash
    with pytest.raises(${error.errorType}):
        ${cleanFnName}()
`;
  } else if (framework === 'node:test') {
    testCode = `// Auto-generated by repro-gen
// Reproducing: ${error.errorType}: ${error.errorMessage}
// Location: ${targetFile}:${frame.lineNumber}

import { describe, it } from 'node:test';
import assert from 'node:assert';
import { ${cleanFnName} } from '${relativeImport}';

describe('Reproduction: ${error.errorType}', () => {
  it('reproduces crash at ${path.basename(targetFile)}:${frame.lineNumber}', async () => {
    // TODO: Pass the input arguments that caused the crash
    assert.doesNotThrow(() => {
      // @ts-ignore
      ${cleanFnName}();
    }, /${error.errorMessage.slice(0, 25).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}/);
  });
});
`;
  } else {
    // Vitest / Jest (compatible)
    const importHeader = framework === 'vitest'
      ? `import { describe, it, expect } from 'vitest';\n`
      : `// Uses Jest globals (describe, it, expect)\n`;

    testCode = `// Auto-generated by repro-gen
// Reproducing: ${error.errorType}: ${error.errorMessage}
// Location: ${targetFile}:${frame.lineNumber}

${importHeader}import { ${cleanFnName} } from '${relativeImport}';

describe('Bug Reproduction: ${error.errorType}', () => {
  it('should reproduce error at ${path.basename(targetFile)}:${frame.lineNumber}', async () => {
    // Expected error: "${error.errorMessage}"
    // TODO: Pass actual bug-triggering inputs to the function call below:
    expect(() => {
      // @ts-ignore
      ${cleanFnName}();
    }).toThrow();
  });

  it('should pass once the bug is fixed', async () => {
    // TODO: Verify the expected safe behavior once bug is resolved
    expect(() => {
      // @ts-ignore
      ${cleanFnName}();
    }).not.toThrow();
  });
});
`;
  }

  let written = false;
  if (!options.dryRun) {
    fs.writeFileSync(outputPath, testCode, 'utf-8');
    written = true;
  }

  return {
    filePath: outputPath,
    code: testCode,
    framework,
    written,
  };
}
